/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-25 01:11:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public final class find_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


   String driver ="oracle.jdbc.driver.OracleDriver";
   Connection conn;
   Statement statement;
   PreparedStatement ps;
   String url ="jdbc:oracle:thin:@localhost:1521:xe";
   String uid ="system";
   String upw ="1234";
   String sql ="select count(*) from student where name =?";
   String sql1 ="select * from student where name =?";   
   
   //String sql2 ="select * from student where no =?";
   ResultSet rs ;
   int count ;
   String name;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

try{	
	//String no =request.getParameter("no");	
	name =request.getParameter("name");		
	
   Class.forName(driver);
   conn =DriverManager.getConnection(url,uid,upw); 
   ps =conn.prepareStatement(sql);   
   ps.setString(1,name);
   rs =ps.executeQuery();
   
  rs.next();
  count =rs.getInt(1);  //필드의 순서  
  out.println("갯수:"+count+"<br>"); 
}catch(Exception e){}

      out.write("\r\n");
      out.write("<a href=\"list.jsp\">회원목록보기</a>/<a href=\"student_1.jsp\">검색화면</a> \r\n");
      out.write("<h3>검색 성공</h3>\r\n");
      out.write("<table width =400 border=1 cellspacing =0 bordercolor =pink>\r\n");
      out.write("   <tr align =center>\r\n");
      out.write("   <td>no</td><td>pw</td><td>name</td><td>hp</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");

     if(count>0){    	 
    	 ps =conn.prepareStatement(sql1);  
         ps.setString(1,name);  
         rs=ps.executeQuery();   
         while(rs.next()){
        	 String no =rs.getString(1);
        	 String pw =rs.getString(2);
        	 String name=rs.getString(3);
        	 String hp =rs.getString(4);
         
      out.write("\r\n");
      out.write("        	<tr align =center><td>");
      out.print(no );
      out.write("</td>  \r\n");
      out.write("        	<td>");
      out.print(pw );
      out.write("</td>\r\n");
      out.write("        	<td>");
      out.print(name );
      out.write("</td>    \r\n");
      out.write("        	<td>");
      out.print(hp );
      out.write("</td>  \r\n");
      out.write("        	</tr>\r\n");
      out.write("       ");
 	
        }//while
        	 out.println("<tr><td colspan =4>");
        	 out.println(name+"님은 "+count+" 명 존재합니다.");
        	 out.println("</td></tr>");
     }else{
    	 out.println("<tr><td colspan =4>");
    	 out.println(name+"님은 존재하지 않습니다.");
    	 out.println("</td></tr>");
     }
   
      out.write("\r\n");
      out.write("</table>\r\n");

	rs.close();
	ps.close();
	conn.close();	


      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
